name: iot_app
description: "IoT App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔥 Firebase Core
  firebase_core: ^2.30.0

  # 🔥 Firebase Auth
  firebase_auth: ^4.20.0

  # 🔥 Realtime Database
  firebase_database: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true